---
title: "p8105_hw1_ql2370"
author: "QiLu"
date: "9/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

First of all, the library we used should be imported

```{r cars, echo}
library(tidyverse)

#create a data frame
basic_df = tibble(
  random_sample = rnorm(8),
  vec_logical = random_sample > 0,
  vec_char = c("This", "is", "H", "W", "1", "done", "by", "QiLu"),
  vec_factor = factor(c("I", "I", "I", "II", "II", "II", "III", "III") )
  
)

pull(basic_df, random_sample)
pull(basic_df, vec_logical)
pull(basic_df, vec_factor)

mean(as.numeric(pull(basic_df,vec_logical)))
mean(as.numeric(pull(basic_df,vec_char)))
mean(as.numeric(pull(basic_df,vec_factor)))
```

# The second code chunk

```{r}
# convert logical vector to numberic
x = as.numeric(pull(basic_df, vec_factor))
y = x * as.numeric(pull(basic_df, random_sample))

x
y

# convert logical vertor to factor
x1 = as.factor(pull(basic_df, vec_factor))
y1 = x * as.factor(pull(basic_df, random_sample))

x1
y1

# convert logical vertor to factor to numberic
x2 = as.numeric(as.factor(pull(basic_df, vec_factor)))
y2 = x2 * as.numeric(pull(basic_df, random_sample))

x2
y2


```

## Problem 2

You can also embed plots, for example:

```{r plot_prob2}

set.seed(1)

plot_df = tibble(
  x = rnorm(500),
  y = rnorm(500),
  vec_logical = (x + y)> 0,
  vec_numberic = c(as.numeric(vec_logical)),
  vec_factor = c(as.factor(vec_numberic))
)

# color points using logical variables
p1 <- ggplot(plot_df, aes (x = x, y = y, color = vec_logical)) + geom_point()
p1

# color points using numberic variables
ggplot(plot_df, aes (x = x, y = y, color = vec_numberic)) + geom_point()

# color points using factor variables
ggplot(plot_df, aes (x = x, y = y, color = vec_factor)) + geom_point()

# export scatterplot by ggsave


ggsave(filename = "hw1_problem2_plot", plot = p1,
    device = "pdf", path = NULL,
    scale = 1)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
